import json
import logging
import os
import random
import time
import urllib.request
import uuid

from snapshot_restore_py import register_after_restore

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Captured at module import. With SnapStart, module import happens once at
# snapshot creation time, so SNAPSHOT_UUID is baked into the snapshot and
# every restored container reports the SAME value — useful for visually
# confirming snapshot sharing.
SNAPSHOT_UUID = str(uuid.uuid4())
SNAPSHOT_TIME = time.time()
INIT_TYPE = os.environ.get("AWS_LAMBDA_INITIALIZATION_TYPE", "unknown")

# These are intentionally re-generated by the after_restore hook so each
# restored container ends up with its own unique values.
CONTAINER_UUID = str(uuid.uuid4())
CONTAINER_RESTORED_AT = time.time()
INVOCATION_COUNT = 0

logger.info(
    "module-init snapshot_uuid=%s container_uuid=%s init_type=%s pid=%d",
    SNAPSHOT_UUID,
    CONTAINER_UUID,
    INIT_TYPE,
    os.getpid(),
)


@register_after_restore
def after_restore():
    # Re-seeds Python's random module from os.urandom. Without this the
    # New Relic agent (which uses random.getrandbits for trace/span IDs)
    # produces identical IDs across all containers restored from the same
    # snapshot — observed empirically as collapsed traces in NR.
    global CONTAINER_UUID, CONTAINER_RESTORED_AT
    random.seed()
    CONTAINER_UUID = str(uuid.uuid4())
    CONTAINER_RESTORED_AT = time.time()
    logger.info(
        "after-restore snapshot_uuid=%s container_uuid=%s",
        SNAPSHOT_UUID,
        CONTAINER_UUID,
    )


def lambda_handler(event, context):
    global INVOCATION_COUNT
    INVOCATION_COUNT += 1

    url = os.environ.get("EXTERNAL_URL", "https://httpbin.org/get")
    request_id = getattr(context, "aws_request_id", "n/a")
    runtime_init_type = os.environ.get("AWS_LAMBDA_INITIALIZATION_TYPE", "unknown")

    logger.info(
        "invoke-start request_id=%s invocation=%d snapshot_uuid=%s "
        "container_uuid=%s runtime_init_type=%s",
        request_id,
        INVOCATION_COUNT,
        SNAPSHOT_UUID,
        CONTAINER_UUID,
        runtime_init_type,
    )

    started = time.perf_counter()
    http_request = urllib.request.Request(
        url, headers={"User-Agent": "lambda-snap-start-test/1.0"}
    )
    with urllib.request.urlopen(http_request, timeout=10) as response:
        status = response.status
        body = response.read().decode("utf-8")
    elapsed_ms = round((time.perf_counter() - started) * 1000, 2)

    logger.info(
        "external-call request_id=%s url=%s status=%d elapsed_ms=%.2f",
        request_id,
        url,
        status,
        elapsed_ms,
    )

    return {
        "statusCode": 200,
        "headers": {"Content-Type": "application/json"},
        "body": json.dumps(
            {
                "snapshot_uuid": SNAPSHOT_UUID,
                "container_uuid": CONTAINER_UUID,
                "init_type": INIT_TYPE,
                "runtime_init_type": runtime_init_type,
                "invocation_count_in_container": INVOCATION_COUNT,
                "snapshot_age_sec": round(time.time() - SNAPSHOT_TIME, 2),
                "container_age_sec": round(time.time() - CONTAINER_RESTORED_AT, 2),
                "external_url": url,
                "external_status": status,
                "elapsed_ms": elapsed_ms,
                "external_body_preview": body[:500],
            }
        ),
    }
